/**
 * Activity log action names for leave-balance use cases.
 */
export const LEAVE_BALANCE_ACTIONS = {
  CREATE: 'CREATE_LEAVE_BALANCE',
  UPDATE: 'UPDATE_LEAVE_BALANCE',
  PAGINATED_LIST: 'PAGINATED_LIST_LEAVE_BALANCE',
  GET_BY_ID: 'GET_LEAVE_BALANCE_BY_ID',
  LOAD_EMPLOYEE_BALANCES_BY_YEAR: 'LOAD_EMPLOYEE_BALANCES_BY_YEAR',
  GET_BY_LEAVE_TYPE: 'GET_LEAVE_BALANCE_BY_LEAVE_TYPE',
  CLOSE: 'CLOSE_LEAVE_BALANCE',
  CLOSE_BALANCES_FOR_EMPLOYEE: 'CLOSE_LEAVE_BALANCES_FOR_EMPLOYEE',
  GENERATE_BALANCES_FOR_YEAR: 'GENERATE_LEAVE_BALANCES_FOR_YEAR',
  RESET_FOR_YEAR: 'RESET_LEAVE_BALANCES_FOR_YEAR',
  ARCHIVE: 'ARCHIVE_LEAVE_BALANCE',
  RESTORE: 'RESTORE_LEAVE_BALANCE',
} as const;
