/**
 * Activity log action names for leave-year-configuration use cases.
 */
export const LEAVE_YEAR_CONFIGURATION_ACTIONS = {
  CREATE: 'CREATE_LEAVE_YEAR_CONFIGURATION',
  UPDATE: 'UPDATE_LEAVE_YEAR_CONFIGURATION',
  ARCHIVE: 'ARCHIVE_LEAVE_YEAR_CONFIGURATION',
  RESTORE: 'RESTORE_LEAVE_YEAR_CONFIGURATION',
  PAGINATED_LIST: 'PAGINATED_LIST_LEAVE_YEAR_CONFIGURATION',
  FIND_ACTIVE_FOR_DATE: 'FIND_ACTIVE_LEAVE_YEAR_FOR_DATE',
} as const;
