/**
 * Activity log action names for leave-policy use cases.
 */
export const LEAVE_POLICY_ACTIONS = {
  CREATE: 'CREATE_LEAVE_POLICY',
  UPDATE: 'UPDATE_LEAVE_POLICY',
  ARCHIVE: 'ARCHIVE_LEAVE_POLICY',
  RESTORE: 'RESTORE_LEAVE_POLICY',
  PAGINATED_LIST: 'PAGINATED_LIST_LEAVE_POLICY',
  ACTIVATE: 'ACTIVATE_LEAVE_POLICY',
  RETIRE: 'RETIRE_LEAVE_POLICY',
  GET_ACTIVE_POLICY: 'GET_ACTIVE_POLICY',
  RETRIEVE_ACTIVE_POLICIES: 'RETRIEVE_ACTIVE_POLICIES',
} as const;
