export const BARANGAY_ACTIONS = {
  CREATE: 'CREATE_BARANGAY',
  UPDATE: 'UPDATE_BARANGAY',
  ARCHIVE: 'ARCHIVE_BARANGAY',
  RESTORE: 'RESTORE_BARANGAY',
  PAGINATED_LIST: 'PAGINATED_LIST_BARANGAY',
  COMBOBOX: 'COMBOBOX_BARANGAY',
} as const;
