export const CITIZENSHIP_ACTIONS = {
  CREATE: 'CREATE_CITIZENSHIP',
  UPDATE: 'UPDATE_CITIZENSHIP',
  ARCHIVE: 'ARCHIVE_CITIZENSHIP',
  RESTORE: 'RESTORE_CITIZENSHIP',
  PAGINATED_LIST: 'PAGINATED_LIST_CITIZENSHIP',
  COMBOBOX: 'COMBOBOX_CITIZENSHIP',
} as const;
