export const CITY_ACTIONS = {
  CREATE: 'CREATE_CITY',
  UPDATE: 'UPDATE_CITY',
  ARCHIVE: 'ARCHIVE_CITY',
  RESTORE: 'RESTORE_CITY',
  PAGINATED_LIST: 'PAGINATED_LIST_CITY',
  COMBOBOX: 'COMBOBOX_CITY',
} as const;
