export const CIVIL_STATUS_ACTIONS = {
  CREATE: 'CREATE_CIVIL_STATUS',
  UPDATE: 'UPDATE_CIVIL_STATUS',
  ARCHIVE: 'ARCHIVE_CIVIL_STATUS',
  RESTORE: 'RESTORE_CIVIL_STATUS',
  PAGINATED_LIST: 'PAGINATED_LIST_CIVIL_STATUS',
  COMBOBOX: 'COMBOBOX_CIVIL_STATUS',
} as const;
