export const MANAGEMENT_201_DATABASE_MODELS = {
  BARANGAYS: 'barangays',
  CITIES: 'cities',
  CITIZENSHIPS: 'citizenships',
  CIVIL_STATUSES: 'civil_statuses',
  EMPLOYMENT_TYPES: 'employment_types',
  EMPLOYMENT_STATUSES: 'employment_statuses',
  PROVINCES: 'provinces',
  RELIGIONS: 'religions',
  REFERENCES: 'references',
  TRAINING_CERTIFICATES: 'training_certificates',
  TRAININGS: 'trainings',
  WORK_EXPERIENCE_COMPANIES: 'work_experience_companies',
  WORK_EXPERIENCE_JOBTITLES: 'work_experience_jobtitles',
  WORK_EXPERIENCES: 'work_experiences',
  EDUCATION_COURSE_LEVELS: 'education_course_levels',
  EDUCATION_COURSES: 'education_courses',
  EDUCATION_LEVELS: 'education_levels',
  EDUCATION_SCHOOLS: 'education_schools',
} as const;
