export const EDUCATION_COURSE_ACTIONS = {
  CREATE: 'CREATE_EDUCATION_COURSE',
  UPDATE: 'UPDATE_EDUCATION_COURSE',
  ARCHIVE: 'ARCHIVE_EDUCATION_COURSE',
  RESTORE: 'RESTORE_EDUCATION_COURSE',
  PAGINATED_LIST: 'PAGINATED_LIST_EDUCATION_COURSE',
  COMBOBOX: 'COMBOBOX_EDUCATION_COURSE',
} as const;
