export const EDUCATION_ACTIONS = {
  CREATE: 'CREATE_EDUCATION',
  UPDATE: 'UPDATE_EDUCATION',
  ARCHIVE: 'ARCHIVE_EDUCATION',
  RESTORE: 'RESTORE_EDUCATION',
  FIND_EMPLOYEES_EDUCATION: 'FIND_EMPLOYEES_EDUCATION',
  PAGINATED_LIST: 'PAGINATED_LIST_EDUCATION',
} as const;
