export const EMPLOYMENT_STATUS_ACTIONS = {
  CREATE: 'CREATE_EMPLOYMENT_STATUS',
  UPDATE: 'UPDATE_EMPLOYMENT_STATUS',
  ARCHIVE: 'ARCHIVE_EMPLOYMENT_STATUS',
  RESTORE: 'RESTORE_EMPLOYMENT_STATUS',
  PAGINATED_LIST: 'PAGINATED_LIST_EMPLOYMENT_STATUS',
  COMBOBOX: 'COMBOBOX_EMPLOYMENT_STATUS',
} as const;
