export const EMPLOYMENT_TYPE_ACTIONS = {
  CREATE: 'CREATE_EMPLOYMENT_TYPE',
  UPDATE: 'UPDATE_EMPLOYMENT_TYPE',
  ARCHIVE: 'ARCHIVE_EMPLOYMENT_TYPE',
  RESTORE: 'RESTORE_EMPLOYMENT_TYPE',
  PAGINATED_LIST: 'PAGINATED_LIST_EMPLOYMENT_TYPE',
  COMBOBOX: 'COMBOBOX_EMPLOYMENT_TYPE',
} as const;
