export const PROVINCE_ACTIONS = {
  CREATE: 'CREATE_PROVINCE',
  UPDATE: 'UPDATE_PROVINCE',
  ARCHIVE: 'ARCHIVE_PROVINCE',
  RESTORE: 'RESTORE_PROVINCE',
  PAGINATED_LIST: 'PAGINATED_LIST_PROVINCE',
  COMBOBOX: 'COMBOBOX_PROVINCE',
} as const;
