export const REFERENCE_ACTIONS = {
  CREATE: 'CREATE_REFERENCE',
  UPDATE: 'UPDATE_REFERENCE',
  ARCHIVE: 'ARCHIVE_REFERENCE',
  RESTORE: 'RESTORE_REFERENCE',
  PAGINATED_LIST: 'PAGINATED_LIST_REFERENCE',
} as const;
