export const TRAINING_ACTIONS = {
  CREATE: 'CREATE_TRAINING',
  UPDATE: 'UPDATE_TRAINING',
  ARCHIVE: 'ARCHIVE_TRAINING',
  RESTORE: 'RESTORE_TRAINING',
  PAGINATED_LIST: 'PAGINATED_LIST_TRAINING',
} as const;
