export const TRAINING_CERTIFICATE_ACTIONS = {
  CREATE: 'CREATE_TRAINING_CERTIFICATE',
  UPDATE: 'UPDATE_TRAINING_CERTIFICATE',
  ARCHIVE: 'ARCHIVE_TRAINING_CERTIFICATE',
  RESTORE: 'RESTORE_TRAINING_CERTIFICATE',
  PAGINATED_LIST: 'PAGINATED_LIST_TRAINING_CERTIFICATE',
  COMBOBOX: 'COMBOBOX_TRAINING_CERTIFICATE',
} as const;
