export const WORK_EXPERIENCE_JOBTITLE_ACTIONS = {
  CREATE: 'CREATE_WORK_EXPERIENCE_JOBTITLE',
  UPDATE: 'UPDATE_WORK_EXPERIENCE_JOBTITLE',
  ARCHIVE: 'ARCHIVE_WORK_EXPERIENCE_JOBTITLE',
  RESTORE: 'RESTORE_WORK_EXPERIENCE_JOBTITLE',
  PAGINATED_LIST: 'PAGINATED_LIST_WORK_EXPERIENCE_JOBTITLE',
  COMBOBOX: 'COMBOBOX_WORK_EXPERIENCE_JOBTITLE',
} as const;
