export const WORK_EXPERIENCE_COMPANY_ACTIONS = {
  CREATE: 'CREATE_WORK_EXPERIENCE_COMPANY',
  UPDATE: 'UPDATE_WORK_EXPERIENCE_COMPANY',
  ARCHIVE: 'ARCHIVE_WORK_EXPERIENCE_COMPANY',
  RESTORE: 'RESTORE_WORK_EXPERIENCE_COMPANY',
  PAGINATED_LIST: 'PAGINATED_LIST_WORK_EXPERIENCE_COMPANY',
  COMBOBOX: 'COMBOBOX_WORK_EXPERIENCE_COMPANY',
} as const;
