export const WORK_EXPERIENCE_ACTIONS = {
  CREATE: 'CREATE_WORK_EXPERIENCE',
  UPDATE: 'UPDATE_WORK_EXPERIENCE',
  ARCHIVE: 'ARCHIVE_WORK_EXPERIENCE',
  RESTORE: 'RESTORE_WORK_EXPERIENCE',
  PAGINATED_LIST: 'PAGINATED_LIST_WORK_EXPERIENCE',
} as const;
