export const BRANCH_ACTIONS = {
  CREATE: 'CREATE_BRANCH',
  UPDATE: 'UPDATE_BRANCH',
  ARCHIVE: 'ARCHIVE_BRANCH',
  RESTORE: 'RESTORE_BRANCH',
  PAGINATED_LIST: 'PAGINATED_LIST_BRANCH',
  COMBOBOX: 'COMBOBOX_BRANCH',
} as const;
