export const DEPARTMENT_ACTIONS = {
  CREATE: 'CREATE_DEPARTMENT',
  UPDATE: 'UPDATE_DEPARTMENT',
  ARCHIVE: 'ARCHIVE_DEPARTMENT',
  RESTORE: 'RESTORE_DEPARTMENT',
  PAGINATED_LIST: 'PAGINATED_LIST_DEPARTMENT',
  COMBOBOX: 'COMBOBOX_DEPARTMENT',
} as const;
