export const JOBTITLE_ACTIONS = {
  CREATE: 'CREATE_JOBTITLE',
  UPDATE: 'UPDATE_JOBTITLE',
  ARCHIVE: 'ARCHIVE_JOBTITLE',
  RESTORE: 'RESTORE_JOBTITLE',
  PAGINATED_LIST: 'PAGINATED_LIST_JOBTITLE',
  COMBOBOX: 'COMBOBOX_JOBTITLE',
} as const;
