export const LEAVE_TYPE_ACTIONS = {
  CREATE: 'CREATE_LEAVE_TYPE',
  UPDATE: 'UPDATE_LEAVE_TYPE',
  ARCHIVE: 'ARCHIVE_LEAVE_TYPE',
  RESTORE: 'RESTORE_LEAVE_TYPE',
  PAGINATED_LIST: 'PAGINATED_LIST_LEAVE_TYPE',
  COMBOBOX: 'COMBOBOX_LEAVE_TYPE',
} as const;
