export * from './barangay.repository';
export * from './city.repository';
export * from './citizenship.repository';
export * from './civil-status.repository';
export * from './employment-type.repository';
export * from './employment-status.repository';
export * from './province.repository';
export * from './religion.repository';
export * from './reference.repository';
