export const EDUCATION_SCHOOL_ACTIONS = {
  CREATE: 'CREATE_EDUCATION_SCHOOL',
  UPDATE: 'UPDATE_EDUCATION_SCHOOL',
  ARCHIVE: 'ARCHIVE_EDUCATION_SCHOOL',
  RESTORE: 'RESTORE_EDUCATION_SCHOOL',
  PAGINATED_LIST: 'PAGINATED_LIST_EDUCATION_SCHOOL',
  COMBOBOX: 'COMBOBOX_EDUCATION_SCHOOL',
} as const;
