export const EDUCATION_COURSE_LEVEL_ACTIONS = {
  CREATE: 'CREATE_EDUCATION_COURSE_LEVEL',
  UPDATE: 'UPDATE_EDUCATION_COURSE_LEVEL',
  ARCHIVE: 'ARCHIVE_EDUCATION_COURSE_LEVEL',
  RESTORE: 'RESTORE_EDUCATION_COURSE_LEVEL',
  PAGINATED_LIST: 'PAGINATED_LIST_EDUCATION_COURSE_LEVEL',
  COMBOBOX: 'COMBOBOX_EDUCATION_COURSE_LEVEL',
} as const;
