export const EDUCATION_LEVEL_ACTIONS = {
  CREATE: 'CREATE_EDUCATION_LEVEL',
  UPDATE: 'UPDATE_EDUCATION_LEVEL',
  ARCHIVE: 'ARCHIVE_EDUCATION_LEVEL',
  RESTORE: 'RESTORE_EDUCATION_LEVEL',
  PAGINATED_LIST: 'PAGINATED_LIST_EDUCATION_LEVEL',
  COMBOBOX: 'COMBOBOX_EDUCATION_LEVEL',
} as const;
