export const RELIGION_ACTIONS = {
  CREATE: 'CREATE_RELIGION',
  UPDATE: 'UPDATE_RELIGION',
  ARCHIVE: 'ARCHIVE_RELIGION',
  RESTORE: 'RESTORE_RELIGION',
  PAGINATED_LIST: 'PAGINATED_LIST_RELIGION',
  COMBOBOX: 'COMBOBOX_RELIGION',
} as const;
