export const TEST_ONE_ACTIONS = {
  CREATE: 'CREATE_TEST_ONE',
  UPDATE: 'UPDATE_TEST_ONE',
  ARCHIVE: 'ARCHIVE_TEST_ONE',
  RESTORE: 'RESTORE_TEST_ONE',
  PAGINATED_LIST: 'PAGINATED_LIST_TEST_ONE',
  COMBOBOX: 'COMBOBOX_TEST_ONE',
} as const;
