export const TEST_THREE_ACTIONS = {
  CREATE: 'CREATE_TEST_THREE',
  UPDATE: 'UPDATE_TEST_THREE',
  ARCHIVE: 'ARCHIVE_TEST_THREE',
  RESTORE: 'RESTORE_TEST_THREE',
  PAGINATED_LIST: 'PAGINATED_LIST_TEST_THREE',
  COMBOBOX: 'COMBOBOX_TEST_THREE',
} as const;
