export const TEST_TWO_ACTIONS = {
  CREATE: 'CREATE_TEST_TWO',
  UPDATE: 'UPDATE_TEST_TWO',
  ARCHIVE: 'ARCHIVE_TEST_TWO',
  RESTORE: 'RESTORE_TEST_TWO',
  PAGINATED_LIST: 'PAGINATED_LIST_TEST_TWO',
  COMBOBOX: 'COMBOBOX_TEST_TWO',
} as const;
